name: '🚀 release'

on:
    release:
        types: [published]

jobs:
    release:
        name: 🚀 release 
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 🟢 node
              uses: actions/setup-node@v1.4.4
              with:
                  node-version: 14
                  registry-url: https://registry.npmjs.org/
                  check-latest: true
            - name: 🚀 publish
              run: npm ci && npm run build && npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
